<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ContainerImageName>attendr/attendr-conferences-api</ContainerImageName>
    <ContainerUser>app</ContainerUser>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <UserSecretsId>4f11dddd-53a6-4296-861c-3ac8e174cf2b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../Shared/HexMaster.Attendr.Core/HexMaster.Attendr.Core.csproj" />
    <ProjectReference Include="../HexMaster.Attendr.Conferences/HexMaster.Attendr.Conferences.csproj" />
    <ProjectReference Include="..\..\Aspire\HexMaster.Attendr.Aspire\HexMaster.Attendr.Aspire.ServiceDefaults\HexMaster.Attendr.Aspire.ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\Shared\HexMaster.Attendr.IntegrationEvents\HexMaster.Attendr.IntegrationEvents.csproj" />
    <ProjectReference Include="..\..\Profiles\HexMaster.Attendr.Profiles.Integrations\HexMaster.Attendr.Profiles.Integrations.csproj" />
    <ProjectReference Include="..\HexMaster.Attendr.Conferences.Data.Postgres\HexMaster.Attendr.Conferences.Data.Postgres.csproj" />
    <ProjectReference Include="..\HexMaster.Attendr.Conferences.IntegrationEvents\HexMaster.Attendr.Conferences.IntegrationEvents.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Azure.Npgsql" Version="13.1.1" />
    <PackageReference Include="Dapr.AspNetCore" Version="1.16.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.3" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.15.0" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.15.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.15.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.15.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.12.41" />
    <PackageReference Include="Sessionize.Api.Client" Version="2.0.1" />
  </ItemGroup>

</Project>
