<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Azure.Npgsql" Version="13.1.2" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Migrations\Scripts\*.sql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HexMaster.Attendr.Conferences\HexMaster.Attendr.Conferences.csproj" />
    <ProjectReference Include="..\HexMaster.Attendr.Conferences.Abstractions\HexMaster.Attendr.Conferences.Abstractions.csproj" />
  </ItemGroup>

</Project>
