<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="HexMaster.Attendr.Groups.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Azure.Npgsql" Version="13.1.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HexMaster.Attendr.Groups\HexMaster.Attendr.Groups.csproj" />
  </ItemGroup>

</Project>
